### ISSUE TITLE
WriteCache Threshold Formatting

### ISSUE THREAD

**Issue by JKJedi** [sacha81/citrix-pvs-healthcheck#15]
When a server exceeds the normal threshold for WriteCache, the background color changes to yellow for that server and for all remaining WriteCache fields - even if they have not exceeded the threshold.

![image](https://cloud.githubusercontent.com/assets/28574136/25866343/c874dde8-34bb-11e7-8e8a-5435625b6fc7.png)

**Comment by digitlman** [comment]
I can confirm this is happening.

**Comment by digitlman** [comment]
Was this fixed in a code update?

**Comment by sacha81** [comment]
V1.3.1:  - Fix for Cache to Ram which is in yellow even then all is ok
