### ISSUE TITLE
Write Cache not displaying disk info

### ISSUE THREAD

**Issue by digitlman** [sacha81/citrix-pvs-healthcheck#19]
Great script, but under Write Cache, it is displaying the disk info as all zeros, but the RAM is right:

0.00 GB, 732 MB on RAM	

My F drive has the vdiskdif.vhdx file, so I have these variables set:

# Relative path to the PVS vDisk write cache file
				$PvsWriteCache   = "f$\.vdiskcache"

		# Relative path to the PVS vDisk write cache file
				$PvsWriteCache   = "f$\vdiskdif.vhdx"

![capture](https://cloud.githubusercontent.com/assets/27826306/26687302/647d8cc2-46bd-11e7-9fd0-48c41a4636cd.JPG)

**Comment by mikekacz** [comment]
Hi,

Two quick questions.
Does it acctually overflows your RAM cache to the file?
Are you sure your account has permissions to query remotely size of the
cache file?

**Comment by digitlman** [comment]
Looks like I am an idiot.  The servers, when freshly booted, read 4MB if you look at the Virtual Disk Status, but I guess your Powershell is rounding down so that counts as essentially zero.

I did a test to copy data over and force overflow from RAM to disk and it did show up OK.

Sorry to bother!

**Comment by digitlman** [comment]
FYI - I added a custom header so that the page auto-refreshes every 60 seconds.    Maybe it is useful enough for you to incorporate into the code as a default?


#==============================================================================================
Function writeHtmlHeader
{
param($title, $fileName)
$date = $ReportDate
$head = @"
<html>
    <head>
    <meta http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>
    <meta http-equiv="refresh" content="60">
    <title>$title</title>
    <STYLE TYPE="text/css">
    
    </style>
    </head>
    <body>
        
        <table width='100%'>
        <tr bgcolor='#CCCCCC'>
        <td width=33% align='center' valign="middle">
        <font face='Tahoma' color='#8A0808' size='2'><strong>Farm Last Queried: $date</strong></font>
        </td>
        <td width=33% align='center' valign="middle">
        <font face='Tahoma' color='#8A0808' size='2'>
        <strong>Page Last Refresfed: 
        <script type="text/javascript">
        
        </script>
        </strong>
        </td>
        <td width=33% align='center' valign="middle">
        <font face='Tahoma' color='#8A0808' size='2'>
        <strong>Auto-Refresh in <span id="CDTimer">180</span> secs.</font></strong>
        <script language="JavaScript" type="text/javascript">
        /*<![CDATA[*/
        var TimerVal = 60;
        var TimerSPan = document.getElementById("CDTimer");
        function CountDown(){
        setTimeout( "CountDown()", 1000 );
        TimerSPan.innerHTML=TimerVal;
        TimerVal=TimerVal-1;
        } CountDown() /*]]>*/ </script>
       
        </table>
"@
$head | Out-File $fileName
}

**Comment by mikekacz** [comment]
No prob.
Good it gets looked at.

**Comment by mikekacz** [comment]
Small suggestion.

Fork. Commit. Pull Request. :)

**Comment by digitlman** [comment]
![capture](https://cloud.githubusercontent.com/assets/27826306/26724133/de418894-4765-11e7-9ef8-3693ff407968.JPG)

In further testing, I have a machine that should be showing the red error box, but is not.   When I run the script, I do see the text that the cache is high.  I also would like to know why the last entry is grey and not green.

**Comment by sacha81** [comment]
fixed in commit  Commit on Jun 13, 2017

**Comment by digitlman** [comment]
I just copied in the newest code and, when the writecache is high, the text box background is still grey instead of red.  When running the script from powershell I do see:

[ERROR] WriteCache on RAM  size is high with 8.22 GB

The only change I made to the code for that function is to change the writecache drive to f$.
