### ISSUE TITLE
WriteCache High background not red on Error

### ISSUE THREAD

**Issue by digitlman** [sacha81/citrix-pvs-healthcheck#21]
I just copied in the newest code and, when the writecache is high, the text box background is still grey instead of red.  When running the script from powershell I do see:

[ERROR] WriteCache on RAM  size is high with 8.22 GB

The only change I made to the code for that function is to change the writecache drive to f$.

**Comment by digitlman** [comment]
Any thoughts?  I took essentially "gold" code, made a minor change, and it still doesn't work.

**Comment by loefflerman** [comment]
found it : there's several typos in Code lines 730, 785, 804. Replace "ERORR" with "ERROR" and the output will be marked RED on ERROR.

**Comment by sacha81** [comment]
Fix included in Version: 1.3.2 - thanks for finding & fixing
