### ISSUE TITLE
I think you you forgot to declare $diskLetters

### ISSUE THREAD

**Issue by rvanderkruk** [sacha81/citrix-pvs-healthcheck#22]
or maybe you did some copy/paste so that now it is removed? All the math about diskfreespace is working but nowhere the $diskLetters is actually declared.

Thanks,
Roland

**Comment by mikekacz** [comment]
they aredefined in "Citrix-PVS77-Farm-Health-toHTML_Parameters.xml"

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Wolny
od wirusów. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rvanderkruk** [comment]
thanks, I think you refer to this then? 
<Variable>
			
			<Name>diskLetters</Name>
			<Value>C,D,F</Value>
			<Type>[array]</Type>
			<Scope>Script</Scope

but I do have a C and D drive so I leave that at 
<Value>C,D</Value>

is something wrong here? I tried several things, like d: or d:\

**Comment by mikekacz** [comment]
Hi,

It works fine for me.
Can you share some detials about the error?

![image](https://user-images.githubusercontent.com/11587900/29511267-f11fc592-865e-11e7-9697-7d77fce7c496.png)

**Comment by rvanderkruk** [comment]
well the PVS server has vdisk store on 'd:\vdisk store' and 100 GB free space. If I do the calculations later in the script all is calculated OK but in the report I get orange indication that there is 0 free space. 
![pvsdiskfreespacenotcorrect](https://user-images.githubusercontent.com/12881156/29511940-0ab1db92-8661-11e7-8bdb-ca41a4246dea.png)

I just downloaded the script today.

**Comment by rvanderkruk** [comment]
does it refer to this? see the values I used and it's the letters of the PVS server, the targets cache on d:
![diskletters](https://user-images.githubusercontent.com/12881156/29512098-923d76b6-8661-11e7-80b4-93ceaf72fc82.png)

**Comment by rvanderkruk** [comment]
hmm sorry I apparently wasted your time. I configured the settings initially to D only where the vdisk store is. Now it's at C and then it's ok.

**Comment by mikekacz** [comment]
Hi,
yes, $diskletters contain set of drives to check in PVS server (not on your target devices). 
it should be typed in without ":'

Do you have errors during run-time from line 432
`        
foreach ($disk in $diskLetters)
        {
            # Check Disk Usage 
            $HardDisk = Get-WmiObject Win32_LogicalDisk -ComputerName $PVServerName_short -Filter "DeviceID='$($disk):'" | Select-Object Size,FreeSpace 
`

From your output it looks that either, you $diskLetters variable is empty or you do not have permission to check the disk info.

**Comment by mikekacz** [comment]
Can it be closed, then ?
:)

**Comment by rvanderkruk** [comment]
yes, I expected that all drives would be checked if I left C,D but it scans only one drive for disk free space. Thanks very much, I didn't test enough, but maybe you should put only one drive letter in the preconfigured values ;-)
